# Generated by Django 4.0.5 on 2022-08-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='Video_background_image',
            field=models.ImageField(default='default.jpg ', null=True, upload_to='USER_FAVORITE_VIDEO%Y'),
        ),
        migrations.AlterField(
            model_name='database',
            name='description',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='database',
            name='movie_trailer_link',
            field=models.URLField(max_length=100),
        ),
    ]
