# Generated by Django 4.0.5 on 2022-08-06 12:10

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_database_video_background_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='database',
            options={'ordering': ['-date_uploaded']},
        ),
        migrations.RemoveField(
            model_name='database',
            name='Video_background_image',
        ),
        migrations.RemoveField(
            model_name='database',
            name='video',
        ),
        migrations.AlterField(
            model_name='database',
            name='movie_trailer_link',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
