# Generated by Django 4.0.5 on 2022-08-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_database_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='video_backgraound_image',
            field=models.ImageField(default='default.jpg ', null=True, upload_to='video_photoes'),
        ),
    ]
