# Generated by Django 4.0.5 on 2022-08-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_database_video_backgraound_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='video',
            field=models.FileField(null=True, upload_to='videos_uploaded'),
        ),
    ]
